apiVersion: v1
kind: Service
metadata:
  name: todo-ui
  labels:
    app: todo-ui
    app.kubernetes.io/name: todo-ui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: quarkus-spring-comparison
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: todo-ui
  type: ClusterIP
