apiVersion: v1
kind: Service
metadata:
  name: quarkus-todo-native
  labels:
    app: quarkus-todo-native
    app.kubernetes.io/name: quarkus-todo-native
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: quarkus-spring-comparison
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: quarkus-todo-native
  type: ClusterIP
